/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DamFormRouteImport } from './routes/dam-form'
import { Route as CowFormRouteImport } from './routes/cow-form'
import { Route as CalfFormRouteImport } from './routes/calf-form'
import { Route as AiRecordFormRouteImport } from './routes/ai-record-form'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthTranspondersIndexRouteImport } from './routes/_auth/transponders/index'
import { Route as AuthSystemSettingsIndexRouteImport } from './routes/_auth/system-settings/index'
import { Route as AuthSemenIndexRouteImport } from './routes/_auth/semen/index'
import { Route as AuthPregnancyDiagnosisIndexRouteImport } from './routes/_auth/pregnancy-diagnosis/index'
import { Route as AuthPdStatusesIndexRouteImport } from './routes/_auth/pd-statuses/index'
import { Route as AuthInseminatorsIndexRouteImport } from './routes/_auth/inseminators/index'
import { Route as AuthFeedlotsIndexRouteImport } from './routes/_auth/feedlots/index'
import { Route as AuthFeedlotManagementIndexRouteImport } from './routes/_auth/feedlot-management/index'
import { Route as AuthDamAiRecordIndexRouteImport } from './routes/_auth/dam-ai-record/index'
import { Route as AuthCowsIndexRouteImport } from './routes/_auth/cows/index'
import { Route as AuthCowStatusesIndexRouteImport } from './routes/_auth/cow-statuses/index'
import { Route as AuthCowRolesIndexRouteImport } from './routes/_auth/cow-roles/index'
import { Route as AuthCowGendersIndexRouteImport } from './routes/_auth/cow-genders/index'
import { Route as AuthColorsIndexRouteImport } from './routes/_auth/colors/index'
import { Route as AuthCalfRecordsIndexRouteImport } from './routes/_auth/calf-records/index'
import { Route as AuthAiStatusesIndexRouteImport } from './routes/_auth/ai-statuses/index'
import { Route as AuthAiRecordsIndexRouteImport } from './routes/_auth/ai-records/index'
import { Route as AuthTranspondersTransponderIdRouteImport } from './routes/_auth/transponders/$transponderId'
import { Route as AuthSemenSemenIdRouteImport } from './routes/_auth/semen/$semenId'
import { Route as AuthInseminatorsInseminatorIdRouteImport } from './routes/_auth/inseminators/$inseminatorId'
import { Route as AuthFeedlotsFeedlotIdRouteImport } from './routes/_auth/feedlots/$feedlotId'
import { Route as AuthCowsCowIdRouteImport } from './routes/_auth/cows/$cowId'
import { Route as AuthCowStatusesStatusIdRouteImport } from './routes/_auth/cow-statuses/$statusId'
import { Route as AuthCowRolesRoleIdRouteImport } from './routes/_auth/cow-roles/$roleId'
import { Route as AuthCowGendersGenderIdRouteImport } from './routes/_auth/cow-genders/$genderId'
import { Route as AuthColorsColorIdRouteImport } from './routes/_auth/colors/$colorId'
import { Route as AuthAiRecordsAiRecordIdRouteImport } from './routes/_auth/ai-records/$aiRecordId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DamFormRoute = DamFormRouteImport.update({
  id: '/dam-form',
  path: '/dam-form',
  getParentRoute: () => rootRouteImport,
} as any)
const CowFormRoute = CowFormRouteImport.update({
  id: '/cow-form',
  path: '/cow-form',
  getParentRoute: () => rootRouteImport,
} as any)
const CalfFormRoute = CalfFormRouteImport.update({
  id: '/calf-form',
  path: '/calf-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecordFormRoute = AiRecordFormRouteImport.update({
  id: '/ai-record-form',
  path: '/ai-record-form',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTranspondersIndexRoute = AuthTranspondersIndexRouteImport.update({
  id: '/transponders/',
  path: '/transponders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSystemSettingsIndexRoute = AuthSystemSettingsIndexRouteImport.update({
  id: '/system-settings/',
  path: '/system-settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSemenIndexRoute = AuthSemenIndexRouteImport.update({
  id: '/semen/',
  path: '/semen/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPregnancyDiagnosisIndexRoute =
  AuthPregnancyDiagnosisIndexRouteImport.update({
    id: '/pregnancy-diagnosis/',
    path: '/pregnancy-diagnosis/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPdStatusesIndexRoute = AuthPdStatusesIndexRouteImport.update({
  id: '/pd-statuses/',
  path: '/pd-statuses/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInseminatorsIndexRoute = AuthInseminatorsIndexRouteImport.update({
  id: '/inseminators/',
  path: '/inseminators/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFeedlotsIndexRoute = AuthFeedlotsIndexRouteImport.update({
  id: '/feedlots/',
  path: '/feedlots/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFeedlotManagementIndexRoute =
  AuthFeedlotManagementIndexRouteImport.update({
    id: '/feedlot-management/',
    path: '/feedlot-management/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDamAiRecordIndexRoute = AuthDamAiRecordIndexRouteImport.update({
  id: '/dam-ai-record/',
  path: '/dam-ai-record/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowsIndexRoute = AuthCowsIndexRouteImport.update({
  id: '/cows/',
  path: '/cows/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowStatusesIndexRoute = AuthCowStatusesIndexRouteImport.update({
  id: '/cow-statuses/',
  path: '/cow-statuses/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowRolesIndexRoute = AuthCowRolesIndexRouteImport.update({
  id: '/cow-roles/',
  path: '/cow-roles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowGendersIndexRoute = AuthCowGendersIndexRouteImport.update({
  id: '/cow-genders/',
  path: '/cow-genders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthColorsIndexRoute = AuthColorsIndexRouteImport.update({
  id: '/colors/',
  path: '/colors/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalfRecordsIndexRoute = AuthCalfRecordsIndexRouteImport.update({
  id: '/calf-records/',
  path: '/calf-records/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiStatusesIndexRoute = AuthAiStatusesIndexRouteImport.update({
  id: '/ai-statuses/',
  path: '/ai-statuses/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiRecordsIndexRoute = AuthAiRecordsIndexRouteImport.update({
  id: '/ai-records/',
  path: '/ai-records/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTranspondersTransponderIdRoute =
  AuthTranspondersTransponderIdRouteImport.update({
    id: '/transponders/$transponderId',
    path: '/transponders/$transponderId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthSemenSemenIdRoute = AuthSemenSemenIdRouteImport.update({
  id: '/semen/$semenId',
  path: '/semen/$semenId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInseminatorsInseminatorIdRoute =
  AuthInseminatorsInseminatorIdRouteImport.update({
    id: '/inseminators/$inseminatorId',
    path: '/inseminators/$inseminatorId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFeedlotsFeedlotIdRoute = AuthFeedlotsFeedlotIdRouteImport.update({
  id: '/feedlots/$feedlotId',
  path: '/feedlots/$feedlotId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowsCowIdRoute = AuthCowsCowIdRouteImport.update({
  id: '/cows/$cowId',
  path: '/cows/$cowId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowStatusesStatusIdRoute = AuthCowStatusesStatusIdRouteImport.update({
  id: '/cow-statuses/$statusId',
  path: '/cow-statuses/$statusId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowRolesRoleIdRoute = AuthCowRolesRoleIdRouteImport.update({
  id: '/cow-roles/$roleId',
  path: '/cow-roles/$roleId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCowGendersGenderIdRoute = AuthCowGendersGenderIdRouteImport.update({
  id: '/cow-genders/$genderId',
  path: '/cow-genders/$genderId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthColorsColorIdRoute = AuthColorsColorIdRouteImport.update({
  id: '/colors/$colorId',
  path: '/colors/$colorId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAiRecordsAiRecordIdRoute = AuthAiRecordsAiRecordIdRouteImport.update({
  id: '/ai-records/$aiRecordId',
  path: '/ai-records/$aiRecordId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/ai-record-form': typeof AiRecordFormRoute
  '/calf-form': typeof CalfFormRoute
  '/cow-form': typeof CowFormRoute
  '/dam-form': typeof DamFormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-records/$aiRecordId': typeof AuthAiRecordsAiRecordIdRoute
  '/colors/$colorId': typeof AuthColorsColorIdRoute
  '/cow-genders/$genderId': typeof AuthCowGendersGenderIdRoute
  '/cow-roles/$roleId': typeof AuthCowRolesRoleIdRoute
  '/cow-statuses/$statusId': typeof AuthCowStatusesStatusIdRoute
  '/cows/$cowId': typeof AuthCowsCowIdRoute
  '/feedlots/$feedlotId': typeof AuthFeedlotsFeedlotIdRoute
  '/inseminators/$inseminatorId': typeof AuthInseminatorsInseminatorIdRoute
  '/semen/$semenId': typeof AuthSemenSemenIdRoute
  '/transponders/$transponderId': typeof AuthTranspondersTransponderIdRoute
  '/ai-records/': typeof AuthAiRecordsIndexRoute
  '/ai-statuses/': typeof AuthAiStatusesIndexRoute
  '/calf-records/': typeof AuthCalfRecordsIndexRoute
  '/colors/': typeof AuthColorsIndexRoute
  '/cow-genders/': typeof AuthCowGendersIndexRoute
  '/cow-roles/': typeof AuthCowRolesIndexRoute
  '/cow-statuses/': typeof AuthCowStatusesIndexRoute
  '/cows/': typeof AuthCowsIndexRoute
  '/dam-ai-record/': typeof AuthDamAiRecordIndexRoute
  '/feedlot-management/': typeof AuthFeedlotManagementIndexRoute
  '/feedlots/': typeof AuthFeedlotsIndexRoute
  '/inseminators/': typeof AuthInseminatorsIndexRoute
  '/pd-statuses/': typeof AuthPdStatusesIndexRoute
  '/pregnancy-diagnosis/': typeof AuthPregnancyDiagnosisIndexRoute
  '/semen/': typeof AuthSemenIndexRoute
  '/system-settings/': typeof AuthSystemSettingsIndexRoute
  '/transponders/': typeof AuthTranspondersIndexRoute
  '/users/': typeof AuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/ai-record-form': typeof AiRecordFormRoute
  '/calf-form': typeof CalfFormRoute
  '/cow-form': typeof CowFormRoute
  '/dam-form': typeof DamFormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/ai-records/$aiRecordId': typeof AuthAiRecordsAiRecordIdRoute
  '/colors/$colorId': typeof AuthColorsColorIdRoute
  '/cow-genders/$genderId': typeof AuthCowGendersGenderIdRoute
  '/cow-roles/$roleId': typeof AuthCowRolesRoleIdRoute
  '/cow-statuses/$statusId': typeof AuthCowStatusesStatusIdRoute
  '/cows/$cowId': typeof AuthCowsCowIdRoute
  '/feedlots/$feedlotId': typeof AuthFeedlotsFeedlotIdRoute
  '/inseminators/$inseminatorId': typeof AuthInseminatorsInseminatorIdRoute
  '/semen/$semenId': typeof AuthSemenSemenIdRoute
  '/transponders/$transponderId': typeof AuthTranspondersTransponderIdRoute
  '/ai-records': typeof AuthAiRecordsIndexRoute
  '/ai-statuses': typeof AuthAiStatusesIndexRoute
  '/calf-records': typeof AuthCalfRecordsIndexRoute
  '/colors': typeof AuthColorsIndexRoute
  '/cow-genders': typeof AuthCowGendersIndexRoute
  '/cow-roles': typeof AuthCowRolesIndexRoute
  '/cow-statuses': typeof AuthCowStatusesIndexRoute
  '/cows': typeof AuthCowsIndexRoute
  '/dam-ai-record': typeof AuthDamAiRecordIndexRoute
  '/feedlot-management': typeof AuthFeedlotManagementIndexRoute
  '/feedlots': typeof AuthFeedlotsIndexRoute
  '/inseminators': typeof AuthInseminatorsIndexRoute
  '/pd-statuses': typeof AuthPdStatusesIndexRoute
  '/pregnancy-diagnosis': typeof AuthPregnancyDiagnosisIndexRoute
  '/semen': typeof AuthSemenIndexRoute
  '/system-settings': typeof AuthSystemSettingsIndexRoute
  '/transponders': typeof AuthTranspondersIndexRoute
  '/users': typeof AuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/ai-record-form': typeof AiRecordFormRoute
  '/calf-form': typeof CalfFormRoute
  '/cow-form': typeof CowFormRoute
  '/dam-form': typeof DamFormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/ai-records/$aiRecordId': typeof AuthAiRecordsAiRecordIdRoute
  '/_auth/colors/$colorId': typeof AuthColorsColorIdRoute
  '/_auth/cow-genders/$genderId': typeof AuthCowGendersGenderIdRoute
  '/_auth/cow-roles/$roleId': typeof AuthCowRolesRoleIdRoute
  '/_auth/cow-statuses/$statusId': typeof AuthCowStatusesStatusIdRoute
  '/_auth/cows/$cowId': typeof AuthCowsCowIdRoute
  '/_auth/feedlots/$feedlotId': typeof AuthFeedlotsFeedlotIdRoute
  '/_auth/inseminators/$inseminatorId': typeof AuthInseminatorsInseminatorIdRoute
  '/_auth/semen/$semenId': typeof AuthSemenSemenIdRoute
  '/_auth/transponders/$transponderId': typeof AuthTranspondersTransponderIdRoute
  '/_auth/ai-records/': typeof AuthAiRecordsIndexRoute
  '/_auth/ai-statuses/': typeof AuthAiStatusesIndexRoute
  '/_auth/calf-records/': typeof AuthCalfRecordsIndexRoute
  '/_auth/colors/': typeof AuthColorsIndexRoute
  '/_auth/cow-genders/': typeof AuthCowGendersIndexRoute
  '/_auth/cow-roles/': typeof AuthCowRolesIndexRoute
  '/_auth/cow-statuses/': typeof AuthCowStatusesIndexRoute
  '/_auth/cows/': typeof AuthCowsIndexRoute
  '/_auth/dam-ai-record/': typeof AuthDamAiRecordIndexRoute
  '/_auth/feedlot-management/': typeof AuthFeedlotManagementIndexRoute
  '/_auth/feedlots/': typeof AuthFeedlotsIndexRoute
  '/_auth/inseminators/': typeof AuthInseminatorsIndexRoute
  '/_auth/pd-statuses/': typeof AuthPdStatusesIndexRoute
  '/_auth/pregnancy-diagnosis/': typeof AuthPregnancyDiagnosisIndexRoute
  '/_auth/semen/': typeof AuthSemenIndexRoute
  '/_auth/system-settings/': typeof AuthSystemSettingsIndexRoute
  '/_auth/transponders/': typeof AuthTranspondersIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-record-form'
    | '/calf-form'
    | '/cow-form'
    | '/dam-form'
    | '/login'
    | '/register'
    | '/ai-records/$aiRecordId'
    | '/colors/$colorId'
    | '/cow-genders/$genderId'
    | '/cow-roles/$roleId'
    | '/cow-statuses/$statusId'
    | '/cows/$cowId'
    | '/feedlots/$feedlotId'
    | '/inseminators/$inseminatorId'
    | '/semen/$semenId'
    | '/transponders/$transponderId'
    | '/ai-records/'
    | '/ai-statuses/'
    | '/calf-records/'
    | '/colors/'
    | '/cow-genders/'
    | '/cow-roles/'
    | '/cow-statuses/'
    | '/cows/'
    | '/dam-ai-record/'
    | '/feedlot-management/'
    | '/feedlots/'
    | '/inseminators/'
    | '/pd-statuses/'
    | '/pregnancy-diagnosis/'
    | '/semen/'
    | '/system-settings/'
    | '/transponders/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-record-form'
    | '/calf-form'
    | '/cow-form'
    | '/dam-form'
    | '/login'
    | '/register'
    | '/'
    | '/ai-records/$aiRecordId'
    | '/colors/$colorId'
    | '/cow-genders/$genderId'
    | '/cow-roles/$roleId'
    | '/cow-statuses/$statusId'
    | '/cows/$cowId'
    | '/feedlots/$feedlotId'
    | '/inseminators/$inseminatorId'
    | '/semen/$semenId'
    | '/transponders/$transponderId'
    | '/ai-records'
    | '/ai-statuses'
    | '/calf-records'
    | '/colors'
    | '/cow-genders'
    | '/cow-roles'
    | '/cow-statuses'
    | '/cows'
    | '/dam-ai-record'
    | '/feedlot-management'
    | '/feedlots'
    | '/inseminators'
    | '/pd-statuses'
    | '/pregnancy-diagnosis'
    | '/semen'
    | '/system-settings'
    | '/transponders'
    | '/users'
  id:
    | '__root__'
    | '/_auth'
    | '/ai-record-form'
    | '/calf-form'
    | '/cow-form'
    | '/dam-form'
    | '/login'
    | '/register'
    | '/_auth/'
    | '/_auth/ai-records/$aiRecordId'
    | '/_auth/colors/$colorId'
    | '/_auth/cow-genders/$genderId'
    | '/_auth/cow-roles/$roleId'
    | '/_auth/cow-statuses/$statusId'
    | '/_auth/cows/$cowId'
    | '/_auth/feedlots/$feedlotId'
    | '/_auth/inseminators/$inseminatorId'
    | '/_auth/semen/$semenId'
    | '/_auth/transponders/$transponderId'
    | '/_auth/ai-records/'
    | '/_auth/ai-statuses/'
    | '/_auth/calf-records/'
    | '/_auth/colors/'
    | '/_auth/cow-genders/'
    | '/_auth/cow-roles/'
    | '/_auth/cow-statuses/'
    | '/_auth/cows/'
    | '/_auth/dam-ai-record/'
    | '/_auth/feedlot-management/'
    | '/_auth/feedlots/'
    | '/_auth/inseminators/'
    | '/_auth/pd-statuses/'
    | '/_auth/pregnancy-diagnosis/'
    | '/_auth/semen/'
    | '/_auth/system-settings/'
    | '/_auth/transponders/'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AiRecordFormRoute: typeof AiRecordFormRoute
  CalfFormRoute: typeof CalfFormRoute
  CowFormRoute: typeof CowFormRoute
  DamFormRoute: typeof DamFormRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dam-form': {
      id: '/dam-form'
      path: '/dam-form'
      fullPath: '/dam-form'
      preLoaderRoute: typeof DamFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cow-form': {
      id: '/cow-form'
      path: '/cow-form'
      fullPath: '/cow-form'
      preLoaderRoute: typeof CowFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calf-form': {
      id: '/calf-form'
      path: '/calf-form'
      fullPath: '/calf-form'
      preLoaderRoute: typeof CalfFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-record-form': {
      id: '/ai-record-form'
      path: '/ai-record-form'
      fullPath: '/ai-record-form'
      preLoaderRoute: typeof AiRecordFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transponders/': {
      id: '/_auth/transponders/'
      path: '/transponders'
      fullPath: '/transponders/'
      preLoaderRoute: typeof AuthTranspondersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/system-settings/': {
      id: '/_auth/system-settings/'
      path: '/system-settings'
      fullPath: '/system-settings/'
      preLoaderRoute: typeof AuthSystemSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/semen/': {
      id: '/_auth/semen/'
      path: '/semen'
      fullPath: '/semen/'
      preLoaderRoute: typeof AuthSemenIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pregnancy-diagnosis/': {
      id: '/_auth/pregnancy-diagnosis/'
      path: '/pregnancy-diagnosis'
      fullPath: '/pregnancy-diagnosis/'
      preLoaderRoute: typeof AuthPregnancyDiagnosisIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pd-statuses/': {
      id: '/_auth/pd-statuses/'
      path: '/pd-statuses'
      fullPath: '/pd-statuses/'
      preLoaderRoute: typeof AuthPdStatusesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inseminators/': {
      id: '/_auth/inseminators/'
      path: '/inseminators'
      fullPath: '/inseminators/'
      preLoaderRoute: typeof AuthInseminatorsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feedlots/': {
      id: '/_auth/feedlots/'
      path: '/feedlots'
      fullPath: '/feedlots/'
      preLoaderRoute: typeof AuthFeedlotsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feedlot-management/': {
      id: '/_auth/feedlot-management/'
      path: '/feedlot-management'
      fullPath: '/feedlot-management/'
      preLoaderRoute: typeof AuthFeedlotManagementIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dam-ai-record/': {
      id: '/_auth/dam-ai-record/'
      path: '/dam-ai-record'
      fullPath: '/dam-ai-record/'
      preLoaderRoute: typeof AuthDamAiRecordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cows/': {
      id: '/_auth/cows/'
      path: '/cows'
      fullPath: '/cows/'
      preLoaderRoute: typeof AuthCowsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-statuses/': {
      id: '/_auth/cow-statuses/'
      path: '/cow-statuses'
      fullPath: '/cow-statuses/'
      preLoaderRoute: typeof AuthCowStatusesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-roles/': {
      id: '/_auth/cow-roles/'
      path: '/cow-roles'
      fullPath: '/cow-roles/'
      preLoaderRoute: typeof AuthCowRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-genders/': {
      id: '/_auth/cow-genders/'
      path: '/cow-genders'
      fullPath: '/cow-genders/'
      preLoaderRoute: typeof AuthCowGendersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/colors/': {
      id: '/_auth/colors/'
      path: '/colors'
      fullPath: '/colors/'
      preLoaderRoute: typeof AuthColorsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calf-records/': {
      id: '/_auth/calf-records/'
      path: '/calf-records'
      fullPath: '/calf-records/'
      preLoaderRoute: typeof AuthCalfRecordsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai-statuses/': {
      id: '/_auth/ai-statuses/'
      path: '/ai-statuses'
      fullPath: '/ai-statuses/'
      preLoaderRoute: typeof AuthAiStatusesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai-records/': {
      id: '/_auth/ai-records/'
      path: '/ai-records'
      fullPath: '/ai-records/'
      preLoaderRoute: typeof AuthAiRecordsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transponders/$transponderId': {
      id: '/_auth/transponders/$transponderId'
      path: '/transponders/$transponderId'
      fullPath: '/transponders/$transponderId'
      preLoaderRoute: typeof AuthTranspondersTransponderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/semen/$semenId': {
      id: '/_auth/semen/$semenId'
      path: '/semen/$semenId'
      fullPath: '/semen/$semenId'
      preLoaderRoute: typeof AuthSemenSemenIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inseminators/$inseminatorId': {
      id: '/_auth/inseminators/$inseminatorId'
      path: '/inseminators/$inseminatorId'
      fullPath: '/inseminators/$inseminatorId'
      preLoaderRoute: typeof AuthInseminatorsInseminatorIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/feedlots/$feedlotId': {
      id: '/_auth/feedlots/$feedlotId'
      path: '/feedlots/$feedlotId'
      fullPath: '/feedlots/$feedlotId'
      preLoaderRoute: typeof AuthFeedlotsFeedlotIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cows/$cowId': {
      id: '/_auth/cows/$cowId'
      path: '/cows/$cowId'
      fullPath: '/cows/$cowId'
      preLoaderRoute: typeof AuthCowsCowIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-statuses/$statusId': {
      id: '/_auth/cow-statuses/$statusId'
      path: '/cow-statuses/$statusId'
      fullPath: '/cow-statuses/$statusId'
      preLoaderRoute: typeof AuthCowStatusesStatusIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-roles/$roleId': {
      id: '/_auth/cow-roles/$roleId'
      path: '/cow-roles/$roleId'
      fullPath: '/cow-roles/$roleId'
      preLoaderRoute: typeof AuthCowRolesRoleIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cow-genders/$genderId': {
      id: '/_auth/cow-genders/$genderId'
      path: '/cow-genders/$genderId'
      fullPath: '/cow-genders/$genderId'
      preLoaderRoute: typeof AuthCowGendersGenderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/colors/$colorId': {
      id: '/_auth/colors/$colorId'
      path: '/colors/$colorId'
      fullPath: '/colors/$colorId'
      preLoaderRoute: typeof AuthColorsColorIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ai-records/$aiRecordId': {
      id: '/_auth/ai-records/$aiRecordId'
      path: '/ai-records/$aiRecordId'
      fullPath: '/ai-records/$aiRecordId'
      preLoaderRoute: typeof AuthAiRecordsAiRecordIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAiRecordsAiRecordIdRoute: typeof AuthAiRecordsAiRecordIdRoute
  AuthColorsColorIdRoute: typeof AuthColorsColorIdRoute
  AuthCowGendersGenderIdRoute: typeof AuthCowGendersGenderIdRoute
  AuthCowRolesRoleIdRoute: typeof AuthCowRolesRoleIdRoute
  AuthCowStatusesStatusIdRoute: typeof AuthCowStatusesStatusIdRoute
  AuthCowsCowIdRoute: typeof AuthCowsCowIdRoute
  AuthFeedlotsFeedlotIdRoute: typeof AuthFeedlotsFeedlotIdRoute
  AuthInseminatorsInseminatorIdRoute: typeof AuthInseminatorsInseminatorIdRoute
  AuthSemenSemenIdRoute: typeof AuthSemenSemenIdRoute
  AuthTranspondersTransponderIdRoute: typeof AuthTranspondersTransponderIdRoute
  AuthAiRecordsIndexRoute: typeof AuthAiRecordsIndexRoute
  AuthAiStatusesIndexRoute: typeof AuthAiStatusesIndexRoute
  AuthCalfRecordsIndexRoute: typeof AuthCalfRecordsIndexRoute
  AuthColorsIndexRoute: typeof AuthColorsIndexRoute
  AuthCowGendersIndexRoute: typeof AuthCowGendersIndexRoute
  AuthCowRolesIndexRoute: typeof AuthCowRolesIndexRoute
  AuthCowStatusesIndexRoute: typeof AuthCowStatusesIndexRoute
  AuthCowsIndexRoute: typeof AuthCowsIndexRoute
  AuthDamAiRecordIndexRoute: typeof AuthDamAiRecordIndexRoute
  AuthFeedlotManagementIndexRoute: typeof AuthFeedlotManagementIndexRoute
  AuthFeedlotsIndexRoute: typeof AuthFeedlotsIndexRoute
  AuthInseminatorsIndexRoute: typeof AuthInseminatorsIndexRoute
  AuthPdStatusesIndexRoute: typeof AuthPdStatusesIndexRoute
  AuthPregnancyDiagnosisIndexRoute: typeof AuthPregnancyDiagnosisIndexRoute
  AuthSemenIndexRoute: typeof AuthSemenIndexRoute
  AuthSystemSettingsIndexRoute: typeof AuthSystemSettingsIndexRoute
  AuthTranspondersIndexRoute: typeof AuthTranspondersIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAiRecordsAiRecordIdRoute: AuthAiRecordsAiRecordIdRoute,
  AuthColorsColorIdRoute: AuthColorsColorIdRoute,
  AuthCowGendersGenderIdRoute: AuthCowGendersGenderIdRoute,
  AuthCowRolesRoleIdRoute: AuthCowRolesRoleIdRoute,
  AuthCowStatusesStatusIdRoute: AuthCowStatusesStatusIdRoute,
  AuthCowsCowIdRoute: AuthCowsCowIdRoute,
  AuthFeedlotsFeedlotIdRoute: AuthFeedlotsFeedlotIdRoute,
  AuthInseminatorsInseminatorIdRoute: AuthInseminatorsInseminatorIdRoute,
  AuthSemenSemenIdRoute: AuthSemenSemenIdRoute,
  AuthTranspondersTransponderIdRoute: AuthTranspondersTransponderIdRoute,
  AuthAiRecordsIndexRoute: AuthAiRecordsIndexRoute,
  AuthAiStatusesIndexRoute: AuthAiStatusesIndexRoute,
  AuthCalfRecordsIndexRoute: AuthCalfRecordsIndexRoute,
  AuthColorsIndexRoute: AuthColorsIndexRoute,
  AuthCowGendersIndexRoute: AuthCowGendersIndexRoute,
  AuthCowRolesIndexRoute: AuthCowRolesIndexRoute,
  AuthCowStatusesIndexRoute: AuthCowStatusesIndexRoute,
  AuthCowsIndexRoute: AuthCowsIndexRoute,
  AuthDamAiRecordIndexRoute: AuthDamAiRecordIndexRoute,
  AuthFeedlotManagementIndexRoute: AuthFeedlotManagementIndexRoute,
  AuthFeedlotsIndexRoute: AuthFeedlotsIndexRoute,
  AuthInseminatorsIndexRoute: AuthInseminatorsIndexRoute,
  AuthPdStatusesIndexRoute: AuthPdStatusesIndexRoute,
  AuthPregnancyDiagnosisIndexRoute: AuthPregnancyDiagnosisIndexRoute,
  AuthSemenIndexRoute: AuthSemenIndexRoute,
  AuthSystemSettingsIndexRoute: AuthSystemSettingsIndexRoute,
  AuthTranspondersIndexRoute: AuthTranspondersIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AiRecordFormRoute: AiRecordFormRoute,
  CalfFormRoute: CalfFormRoute,
  CowFormRoute: CowFormRoute,
  DamFormRoute: DamFormRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
